# This is a template `pyproject.toml` file for snaps
# This file is managed by bootstack-charms-spec and should not be modified
# within individual snap repos. https://launchpad.net/bootstack-charms-spec

[tool.flake8]
ignore = ["C901", "D100", "D101", "D102", "D103", "W503", "W504"]
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'report']
max-line-length = 120
max-complexity = 10

[tool.black]
line-length = 88
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | report
)/
'''

[tool.isort]
profile = "black"
skip_glob = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | report
)/
'''

[tool.pytest.ini_options]
addopts = '''
    --last-failed 
    --last-failed-no-failures all
'''

[tool.coverage.run]
relative_files = true
source = ["."]
omit = ["tests/**", "docs/**", "contrib/**", "snap/**", "setup.py"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.html]
directory = "tests/unit/report/html"

[tool.coverage.xml]
output = "tests/unit/report/coverage.xml"
